### ISSUE TITLE
fix error on multibyte conversion in 2001-03

### ISSUE THREAD

**Issue by beanumber** [beanumber/airlines#11]
```
Reading flight data from 2001-3.csv
 Show Traceback
 
 Rerun with Debug
 Error in type.convert(data[[i]], as.is = as.is[i], dec = dec, numerals = numerals,  : 
  invalid multibyte string at '<e4>NKNO<e6>' 
```

**Comment by nicholasjhorton** [comment]
This hopefully should do the trick:

air <- readLines("airline_2001_3.csv")
air2 <- gsub("[^[:print:]]", "", air)

writeLines(air2, "clean.csv")
rm(air, air2)

air3 <- read.csv("clean.csv", stringsAsFactors = FALSE)
