### ISSUE TITLE
add the part of 1987 included with the airline data into the vignette?

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/airlines#22]
why start at 1988?

**Comment by nicholasjhorton** [comment]
This should work on your end, no?

airlines %<>%
  etl_update(year = 1987, months = 10:12)

**Comment by beanumber** [comment]
Yes. That should work. 
In the minimal vignette, the workflow is:
```
airlines %<>%
  etl_create(year = 1987)
lapply(1988:2015, etl_update, obj = airlines)
```
Right now, it is not smart enough to avoid inserting duplicate rows, so you have to be careful not to do that. Hence we create the database with 1987 data, and then update it with everything since.

**Comment by beanumber** [comment]
This will likely go away with the new workflow.
