### ISSUE TITLE
vectorize the year argument to etl_update

### ISSUE THREAD

**Issue by beanumber** [beanumber/airlines#25]
the `lapply` should just happen within the function, so that the user can just do
```
etl_update(airlines, years = 1988:2015)
```

**Comment by nicholasjhorton** [comment]
I concur, but I'm also hoping that we can do some testing and try to finalize the interface (or should that wait until there's another package as a prototype?)

Nick

> On Sep 1, 2015, at 9:53 AM, Ben Baumer <notifications@github.com> wrote:
> 
> the lapply should just happen within the function, so that the user can just do
> 
> etl_update(airlines, years = 1988:2015)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
