### ISSUE TITLE
update or remove weather data set

### ISSUE THREAD

**Issue by beanumber** [beanumber/airlines#3]
Not sure how important this is...

**Comment by beanumber** [comment]
This really deserves to be a separate package, since processing the weather data has it's own ETL phases. It's not clear to me how this should work with `airlines`. If you pull the airlines data for 2014, should this pull all of the weather data for 2014 for all of the stations at all of the airports?? 

@hadley is able to do it for `nycflights13` because there are only three airports and only one year. But how does this scale to the general case? 

What do you think @nicholasjhorton ?

The easiest solution would be to junk this altogether, and/or make `weather` a separate `etl` package. If we did both, then the `airlines` and `weather` packages could be symbiotic.

**Comment by nicholasjhorton** [comment]
This feels like a separate etl package to me. If I'm not mistaken nycflights13 could just require this as well as airlines. 

All the best,

Nick
