### ISSUE TITLE
error running commands from vignette

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/airlines#30]
When I ran:

db <- src_mysql(host = "localhost", user = "r-user", password = "mypass", dbname = "airlines")
airlines <- etl("airlines", db, dir = "~/dumps/airlines")
airlines %>%
  etl_create(year = 1987, months = 10)

it successfuly downloaded the October 1987 data but yielded the following message trying to get the airports table set up:

trying URL 'http://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat'
Error in download.file(src, lcl) : 
  cannot open URL 'http://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat'

I'm running Mac OS X 11.11.2 on a Macbook Air.

**Comment by beanumber** [comment]
The error is occurring [here](https://github.com/beanumber/airlines/blob/master/R/etl_load.R#L142).

Is there some reason why you wouldn't be able to download that file? It's not HTTPS. 

This worked on a Mac for me last night.

**Comment by beanumber** [comment]
Need to watch out for clobbering old files and test on other platforms.
