### ISSUE TITLE
default call to "etl()" yields error message

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/airlines#31]
> airlines <- etl("airlines", dir="~/dumps/airlines")
Not a valid src. Creating a src_sqlite for you at /var/folders/2j/g4h6r3717_523kybc87_4rlr0000gp/T//Rtmplwpm3T/file1178252d582bc.sqlite3
Error in .local(drv, ...) : Could not connect to database:
unable to open database file

Any guidance about how to stub out an SQLite airlines database would be greatly appreciated.

**Comment by beanumber** [comment]
I can't reproduce this error. Can you post the traceback?
```
> library(airlines)
> airlines <- etl("airlines", dir="~/dumps/airlines")
Not a valid src. Creating a src_sqlite for you at /tmp/RtmpEkN66N/file68de5affb7f5.sqlite3
> 
```

**Comment by nicholasjhorton** [comment]
Nick can't replicate this.  Closing for now.

**Comment by beanumber** [comment]
still broken
```
> airlines <- etl("airlines")
Not a valid src. Creating a src_sqlite for you at /tmp/RtmpxlFYmk/file346575211ea4.sqlite3
> airlines %>% etl_create(year = 1987, months = 5)
```
